### PR TITLE
3.17.0

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin please rerender

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
@scopatz @jakirkham @notestaff I think that this is ready for review :)

**Comment by jakirkham** [comment]
It would be nice to figure out why macOS and Windows are not working

**Comment by saraedum** [comment]
That will be #9. I am actually doing this one because I want valgrind on macOS :)

**Comment by jakirkham** [comment]
Ok let's give this a try then 🍀 

Thanks for the work here! 😄

**Pull request merged**
